# Generated by Django 4.2.4 on 2023-11-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_catagories_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_sold',
            new_name='sold_out',
        ),
    ]
