# Generated by Django 4.2.4 on 2023-11-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_is_sold_item_sold_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Catagories',
            new_name='catagories',
        ),
    ]
